language: c

before_install:
    - docker pull openrct2/openloco:$DOCKERIMG

sudo: required
dist: trusty

matrix:
    include:
        - os: linux
          services:
            - docker
          env:
            - OPENLOCO_CMAKE_OPTS="-G Ninja -DCMAKE_BUILD_TYPE=release -Dyaml-cpp_DIR=/usr/lib/i386-linux-gnu/cmake/yaml-cpp"
            - DOCKERIMG=ubuntu-i686
        - os: linux
          services:
            - docker
          env:
            - OPENLOCO_CMAKE_OPTS="-G Ninja -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=release -Dyaml-cpp_DIR=/usr/lib/i386-linux-gnu/cmake/yaml-cpp"
            - DOCKERIMG=ubuntu-i686
        - os: linux
          services:
            - docker
          env:
            - OPENLOCO_CMAKE_OPTS="-G Ninja -DCMAKE_TOOLCHAIN_FILE=../CMakeLists_mingw.txt -DCMAKE_BUILD_TYPE=release -DBOOST_ROOT=/usr/i686-w64-mingw32/sys-root/mingw/  -Dyaml-cpp_DIR=/usr/i686-w64-mingw32/sys-root/mingw/CMake/"
            - DOCKERIMG=fedora-mingw32
        - os: linux
          before_install: []
          language: cpp
          sudo: false 
          addons:
            apt:
              sources:
                - llvm-toolchain-trusty-5.0
              packages:
                - clang-format-5.0
          script:
            - ./scripts/run-clang-format.py -r src
        - os: osx
          osx_image: xcode9.3 # macOS 10.13
          language: cpp
          before_install:
            - export HOMEBREW_NO_AUTO_UPDATE=1
          install:
            - brew uninstall --ignore-dependencies boost
            - brew install https://raw.githubusercontent.com/marijnvdwerf/openloco-dependencies/v1/Formula/sdl2.rb
            - brew install https://raw.githubusercontent.com/marijnvdwerf/openloco-dependencies/v1/Formula/boost.rb
            - brew install --univeral https://raw.githubusercontent.com/marijnvdwerf/openloco-dependencies/v2/Formula/yaml-cpp.rb
          script:
            - mkdir build && cd build
            - cmake ../
            - make -j2
        - os: osx
          osx_image: xcode9.2 # macOS 10.12 (lacks std::byte)
          language: cpp
          before_install:
            - export HOMEBREW_NO_AUTO_UPDATE=1
          install:
            - brew uninstall --ignore-dependencies boost
            - brew install https://raw.githubusercontent.com/marijnvdwerf/openloco-dependencies/v1/Formula/sdl2.rb
            - brew install https://raw.githubusercontent.com/marijnvdwerf/openloco-dependencies/v1/Formula/boost.rb
            - brew install --universal https://raw.githubusercontent.com/marijnvdwerf/openloco-dependencies/v2/Formula/yaml-cpp.rb
          script:
            - mkdir build && cd build
            - cmake ../
            - make -j2


script:
    - mkdir build
    - docker run -v $(pwd):/openloco -w /openloco/build -i -t openrct2/openloco:$DOCKERIMG bash -c "cmake ../ ${OPENLOCO_CMAKE_OPTS} && ninja -k0"
